import { normalizeResource } from "@/lib/resource-record";
import type { DifficultyLevel, ResourceCategory, ResourceRecord, RoadmapStage } from "@/lib/types";

const REFERENCE_ITEMS = [
  {
    order: 1,
    sourceCategory: "AI/에이전트 입문",
    difficultyText: "입문",
    title: "AI 트렌드 온보딩 완벽 가이드",
    format: "웹 가이드",
    topic: "AI 타임라인, 핵심 기술 원리, 모델 경쟁, 서비스/비즈니스, 바이브코딩, 하네스 엔지니어링",
    objective: "ChatGPT 이후 AI 흐름과 용어를 큰 그림으로 이해하고, 왜 프롬프트를 넘어 에이전트/하네스가 중요해졌는지 맥락을 잡는다.",
    expectedOutcome: "모델·도구·서비스·개발 방식의 변화를 한 장의 지도처럼 설명할 수 있고, 이후 Claude/Codex 자료를 읽을 공통 언어를 갖게 된다.",
    reason: "비전공자도 따라가기 쉬운 온보딩 자료라서 전체 자료 묶음의 진입점으로 가장 적합하다.",
    prerequisites: "없음",
    analysisMemo: "입문자용 종합 개론서. 기술 원리부터 하네스까지 폭이 넓다.",
    trustLevel: "높음",
    url: "https://revfactory.github.io/ai-trend-onboarding/",
  },
  {
    order: 2,
    sourceCategory: "공식 기초/허브",
    difficultyText: "입문~고급",
    title: "Anthropic Courses",
    format: "공식 코스 허브",
    topic: "Claude 101, AI Fluency, Claude Code, Claude API, MCP 입문/심화",
    objective: "공식 커리큘럼 기준으로 Claude 생태계의 학습 경로를 잡고, 자신에게 필요한 트랙(일반 활용/개발/API/MCP)을 고른다.",
    expectedOutcome: "Claude 일반 활용부터 개발, Claude Code, MCP까지 단계별로 학습 루트를 설계할 수 있다.",
    reason: "공식 자료라 신뢰도가 높고, 초급부터 고급까지 연결되는 허브 역할을 한다.",
    prerequisites: "없음",
    analysisMemo: "단일 코스가 아니라 코스 모음. Claude 101은 입문, Claude Code/MCP는 중급 이상으로 확장된다.",
    trustLevel: "높음",
    url: "https://anthropic.skilljar.com/",
  },
  {
    order: 3,
    sourceCategory: "공식 워크플로우",
    difficultyText: "초급~고급",
    title: "OpenAI Codex Best Practices 한국어 정리",
    format: "LinkedIn 아티클",
    topic: "컨텍스트, 계획, AGENTS.md, 설정, 테스트/리뷰, MCP, Skills, Automations",
    objective: "Codex를 단발성 챗봇이 아니라 설정하고 개선하는 작업 파트너로 다루는 법을 익힌다.",
    expectedOutcome: "프롬프트 품질보다 작업 환경 설계가 더 중요하다는 관점을 익히고, Codex 운영의 표준 루틴을 잡는다.",
    reason: "공식 Best practices를 한국어로 풀어 쓴 자료라 입문자와 실무자 사이의 브리지 역할을 한다.",
    prerequisites: "기본적인 코딩 에이전트 개념",
    analysisMemo: "Claude Code 자료와 교차 비교하기 좋다.",
    trustLevel: "높음",
    url: "https://www.linkedin.com/pulse/openai-codex-best-practices-%ED%95%9C%EA%B5%AD%EC%96%B4-%EC%A0%95%EB%A6%AC-seowoo-han-srtzc/",
  },
  {
    order: 4,
    sourceCategory: "Claude Code 실무",
    difficultyText: "초급~고급",
    title: "Claude Code 완전 가이드 70가지 팁",
    format: "PDF 가이드",
    topic: "에이전틱 사고방식, 환경 설정, 컨텍스트 관리, Git/GitHub, MCP/Hooks/Skills/Agents, 자동화, 샌드박스, 웹 자동화, SDK",
    objective: "Claude Code를 '그냥 터미널 챗' 수준이 아니라 실전 개발 파트너로 다루는 전체 운영법을 익힌다.",
    expectedOutcome: "세션 관리, 작업 분해, CLAUDE.md, worktree, skills, hooks, headless/CI 등 Claude Code의 고효율 사용법을 체계적으로 익힌다.",
    reason: "13개 파트로 정리된 종합 실전서에 가까워서 Claude Code 학습의 중심축으로 쓰기 좋다.",
    prerequisites: "기본 터미널/Git 사용 경험",
    analysisMemo: "첨부 PDF는 세션에서 직접 열리지 않았고, 공개 소개/목차/링크 메타데이터 기준으로 분석했다.",
    trustLevel: "중간~높음",
    url: "https://drive.google.com/file/d/1x2x1T4lzTISnHGN8nd4KtMhL8iwi6QgU/view",
  },
  {
    order: 5,
    sourceCategory: "환경/CLI 최적화",
    difficultyText: "초급~중급",
    title: "Claude Code, 아직 기본 설정으로 쓰고 계세요?",
    format: "Threads 포스트",
    topic: "Claude Code + CLI 환경 세팅, 코어 명령어 현대화, 데이터 처리 도구",
    objective: "Claude Code가 잘 다루는 터미널 환경을 세팅하고, CLI 도구 품질이 에이전트 성능에 미치는 영향을 이해한다.",
    expectedOutcome: "eza, bat, fd, ripgrep, jq 등 Claude Code 친화적 도구를 정리하고 최소 실전 세팅을 완성할 수 있다.",
    reason: "실전 생산성 개선 체감이 크고, Claude Code PDF와 바로 연결해서 적용하기 쉽다.",
    prerequisites: "기본 터미널 명령어",
    analysisMemo: "기본 설정만으로는 도구의 일부만 쓰는 상태라는 문제의식을 전제로 한다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@qjc.ai/post/DVYUPtxE9kF",
  },
  {
    order: 6,
    sourceCategory: "재사용 구조화",
    difficultyText: "초급~중급",
    title: "단언컨데, 아직도 프롬프트에 목 메신다면 뒤쳐지고 있는 겁니다",
    format: "Threads 포스트",
    topic: "프롬프트 vs Skills, 반복 작업의 구조화",
    objective: "매번 같은 설명을 반복하는 대신 Skills로 작업을 승격시키는 기준을 익힌다.",
    expectedOutcome: "어떤 작업이 일회성 프롬프트이고 어떤 작업이 재사용 가능한 Skill인지 구분할 수 있다.",
    reason: "초보자가 가장 먼저 바꿔야 할 사고방식 중 하나를 짧게 정리한 자료다.",
    prerequisites: "기본 프롬프트 사용 경험",
    analysisMemo: "'99%는 프롬프트, 상위 1%는 skills'라는 메시지로 전환점을 강조한다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@unclejobs.ai/post/DV3QspvCcbS",
  },
  {
    order: 7,
    sourceCategory: "재사용 구조화",
    difficultyText: "초급~중급",
    title: "AI를 잘 모르는 사람이라도 Skills 는 꼭 알고있으면 좋습니다",
    format: "Threads 포스트",
    topic: "Skills 개념, PM용 오픈소스 pm-skills",
    objective: "개발자뿐 아니라 PM/비개발자도 Skills를 이용해 AI를 역할 기반으로 활용할 수 있음을 이해한다.",
    expectedOutcome: "Skills를 'AI 업무 노하우 패키징' 도구로 바라보게 되고, 역할별 에이전트 설계 아이디어를 얻는다.",
    reason: "Skills를 비개발자 관점까지 확장해서 보여줘서, 적용 범위를 넓혀 준다.",
    prerequisites: "AI 챗 도구 기본 사용",
    analysisMemo: "pm-skills 사례를 통해 '직무형 skill' 개념을 소개한다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@choi.openai/post/DV6QDWZCYpx",
  },
  {
    order: 8,
    sourceCategory: "재사용 구조화",
    difficultyText: "중급",
    title: "Claude Code 와 Codex 에 일 시키기 전에 Spec 파일 3개부터 만드세요",
    format: "LinkedIn 포스트",
    topic: "CLAUDE.md, SPEC.md, plan.md 3계층 구조, 세션 분리",
    objective: "에이전트에게 의도를 안정적으로 전달하기 위한 문서 구조를 배운다.",
    expectedOutcome: "프로젝트 헌법/기능 스펙/실행 태스크를 분리해 instruction overload를 줄이고 결과 일관성을 높일 수 있다.",
    reason: "프롬프트를 문서 구조로 바꾸는 가장 실전적인 패턴 중 하나다.",
    prerequisites: "Git 저장소, 기능 설계 경험",
    analysisMemo: "지시를 한 파일에 몰아넣지 말고 역할별 파일로 분리하라는 관점이 핵심이다.",
    trustLevel: "높음",
    url: "https://www.linkedin.com/posts/jyoung105_claude-code",
  },
  {
    order: 9,
    sourceCategory: "운영 스택 확장",
    difficultyText: "중급",
    title: "Claude Code 와 Codex 를 구독했다면 전 세계 상위 0.3%, 이 5가지 세팅을 하면 상위 0.01% 입니다",
    format: "LinkedIn 포스트",
    topic: "Specialized Agents/Skills, Agent Teams, MCP, Real-Time Monitoring, Automation",
    objective: "단일 채팅형 사용을 넘어 에이전트 운영 스택을 확장하는 5가지 축을 이해한다.",
    expectedOutcome: "역할별 에이전트, 병렬 실행, 외부 도구 연결, 상태 모니터링, 스케줄 자동화를 하나의 시스템으로 묶어 볼 수 있다.",
    reason: "'다음 단계로 무엇을 붙여야 하는가'를 한 번에 보여주는 체크리스트형 자료다.",
    prerequisites: "Claude Code 또는 Codex 기본 사용 경험",
    analysisMemo: "하네스를 직접 만들기 전, 켜둘 수 있는 기능과 세팅을 정리한 글.",
    trustLevel: "높음",
    url: "https://www.linkedin.com/posts/jyoung105_claude-code-codex",
  },
  {
    order: 10,
    sourceCategory: "제품화/응용",
    difficultyText: "중급",
    title: "Claude Code 이렇게 써보셈",
    format: "Threads 포스트",
    topic: "Skills/에이전트에서 멈추지 않고 데스크톱 앱/실사용 도구로 제품화",
    objective: "개인용 자동화에서 한 단계 더 나아가 사용자-facing 도구로 포장하는 관점을 익힌다.",
    expectedOutcome: "에이전트 워크플로우를 UI/앱으로 감싸 재사용성을 높이는 제품화 아이디어를 얻게 된다.",
    reason: "'스킬 만들기' 다음 단계가 '실제 도구화'라는 점을 보여준다.",
    prerequisites: "하나 이상의 스킬/자동화 사용 경험",
    analysisMemo: "카드뉴스 자동화·데스크톱 앱화 등 실제 결과물 연결을 강조한다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@devdesign.kr/post/DVgLnWECgij",
  },
  {
    order: 11,
    sourceCategory: "시스템 설계/하네스",
    difficultyText: "중급~고급",
    title: "Harness Engineering = 강력하지만 제멋대로 가면 큰일나는 야생마같은 AI",
    format: "Threads 포스트",
    topic: "Harness Engineering, AI 제어 시스템 설계",
    objective: "에이전트를 잘 쓰는 것과 에이전트를 올바르게 제어하는 시스템을 설계하는 것이 다름을 이해한다.",
    expectedOutcome: "프롬프트/플러그인 수준을 넘어, 규칙·도구·검증·상태 관리가 들어간 하네스 관점을 갖게 된다.",
    reason: "고급 학습 구간으로 넘어갈 때 필요한 시스템 사고를 압축해서 보여준다.",
    prerequisites: "Skills, MCP, 자동화 개념",
    analysisMemo: "'강력한 AI를 올바른 방향으로 제어하는 시스템'이라는 정의가 핵심.",
    trustLevel: "중간",
    url: "https://www.threads.com/@_petercha/post/DVoAsMEASc9",
  },
  {
    order: 12,
    sourceCategory: "시스템 설계/하네스",
    difficultyText: "중급~고급",
    title: "세계적인 에이전트 엔지니어가 되는법",
    format: "Threads 포스트",
    topic: "실서비스/데이터 파이프라인, 명확한 종료 조건, 세션/계약 단위 작업",
    objective: "에이전트 엔지니어링을 '툴 수집'이 아니라 경계가 분명한 실제 업무 시스템 설계로 바라본다.",
    expectedOutcome: "명확한 완료 조건, 세션 분리, 서비스/데이터 연결 등 장기 과제를 다루는 설계 원칙을 익힌다.",
    reason: "고급 실무에서 중요한 bounded workflow 원칙이 담겨 있다.",
    prerequisites: "Git/API/데이터 파이프라인 기초",
    analysisMemo: "하네스나 플러그인 집착보다 실제 서비스·파이프라인에 연결하는 능력을 강조한다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@choi.openai/post/DVlRuy2jRpJ",
  },
  {
    order: 13,
    sourceCategory: "고급 아키텍처/인증",
    difficultyText: "고급",
    title: "해외 Claude 유저들을 들끓게 하는 아티클이 있습니다",
    format: "Threads 포스트",
    topic: "Claude Certified Architect, 아키텍처 역량 도메인, 고급 학습 범위",
    objective: "Claude 아키텍트 수준에서 요구되는 지식 범위가 무엇인지 역산해 본다.",
    expectedOutcome: "Agentic Architecture, Claude Code workflows, MCP, Prompting, Reliability 등 고급 학습 항목을 체크리스트처럼 활용할 수 있다.",
    reason: "학습 완료 후 자신의 수준을 점검할 수 있는 '상위 커리큘럼' 역할을 한다.",
    prerequisites: "프로덕션 수준 에이전트 워크플로우 이해",
    analysisMemo: "시험 접근성/세부 조건은 변할 수 있으므로 인증 자체보다 커리큘럼 참고용으로 보는 편이 좋다.",
    trustLevel: "중간",
    url: "https://www.threads.com/@unclejobs.ai/post/DV7tBeEibDh",
  },
  {
    order: 14,
    sourceCategory: "고급 비교/도구철학",
    difficultyText: "고급",
    title: "Claude Code 29개 vs Codex 7개, 설계 철학이 정반대였습니다",
    format: "LinkedIn 포스트",
    topic: "도구 분리 전략, 보안 모델, Skills 배포, 명령 체계, 팀 모드, 훅/권한 설계",
    objective: "Claude Code와 Codex를 기능 목록이 아니라 설계 원칙과 운영 구조 차이로 비교한다.",
    expectedOutcome: "도구 선택 시 '어떤 구조 위에서 일할지'를 판단할 수 있고, 보안/권한/생태계/멀티에이전트 차이를 이해한다.",
    reason: "고급 사용자가 두 도구를 병행하거나 선택할 때 매우 유용한 비교 프레임이다.",
    prerequisites: "Claude Code, Codex 둘 다 사용해 본 경험",
    analysisMemo: "숫자 비교보다 권한 모델·shell 위임 정도·배포 구조 차이를 이해하는 데 가치가 있다.",
    trustLevel: "높음",
    url: "https://www.linkedin.com/posts/jyoung105_claude-code-29-vs-codex-7",
  },
  {
    order: 15,
    sourceCategory: "보조 참고/환경",
    difficultyText: "초급",
    title: "브라우저 탭이 20개 넘어가면 메모리가 한도초과되서...",
    format: "Threads 포스트",
    topic: "AI 작업환경 경량화, 브라우저 탭 과부하 해결 팁",
    objective: "AI 도구를 장시간 병행 사용할 때 작업환경 자체를 가볍게 유지하는 방법을 익힌다.",
    expectedOutcome: "브라우저 탭 남발 대신 앱화/분리 실행 같은 운영 습관을 검토하게 된다.",
    reason: "핵심 커리큘럼은 아니지만, 실사용 피로도를 줄여 주는 환경 팁 성격이다.",
    prerequisites: "없음",
    analysisMemo: "Threads 원문 직접 열람이 제한되어 공개 스니펫 기준으로 보수적으로 분류했다.",
    trustLevel: "낮음~중간",
    url: "https://www.threads.com/@unclejobs.ai/post/DVcXDGiCf9_",
  },
  {
    order: 16,
    sourceCategory: "보조 참고/UI·디자인",
    difficultyText: "초급",
    title: "디자이너가 개인적으로 추천하는 디자인시스템 모음집",
    format: "Threads 포스트",
    topic: "컴포넌트/디자인 시스템 레퍼런스",
    objective: "UI를 만드는 에이전트에게 더 좋은 레퍼런스를 줄 수 있도록 디자인 시스템 감각을 보강한다.",
    expectedOutcome: "프론트엔드/UI 생성 작업에서 더 구체적인 기준과 참조 예시를 제시할 수 있다.",
    reason: "핵심 에이전트 학습 자료는 아니지만, 제품화/프론트엔드 작업의 품질을 높이는 보조 자료다.",
    prerequisites: "Figma 또는 UI 기초가 있으면 더 좋음",
    analysisMemo: "디자인 시스템과 컴포넌트 명칭 감각을 채우는 참고 링크 성격.",
    trustLevel: "중간",
    url: "https://www.threads.com/@ai_uiux_designer/post/DV0lGbDkXAH",
  },
];

function mapCategory(sourceCategory: string): ResourceCategory {
  if (sourceCategory.includes("구조화")) return "Prompting";
  if (sourceCategory.includes("워크플로우")) return "LLM Apps";
  if (sourceCategory.includes("Claude Code") || sourceCategory.includes("운영 스택") || sourceCategory.includes("하네스") || sourceCategory.includes("아키텍처")) return "Agents";
  if (sourceCategory.includes("제품화") || sourceCategory.includes("환경")) return "Deployment";
  return "Foundations";
}

function mapDifficulty(difficultyText: string): DifficultyLevel {
  if (difficultyText.includes("고급")) return "Advanced";
  if (difficultyText.includes("중급")) return "Intermediate";
  return "Beginner";
}

function mapRoadmap(category: ResourceCategory): RoadmapStage {
  const roadmapMap = {
    Foundations: "Foundation",
    Prompting: "Prompting",
    "LLM Apps": "Application",
    Agents: "Agent Systems",
    Deployment: "Production",
  };

  return roadmapMap[category] || "Foundation";
}

function buildTags(item: (typeof REFERENCE_ITEMS)[number]): string[] {
  return [item.format, item.trustLevel, ...item.topic.split(",").map((tag) => tag.trim()).slice(0, 4)];
}

export const REFERENCE_RESOURCES: ResourceRecord[] = REFERENCE_ITEMS.map((item) => {
  const category = mapCategory(item.sourceCategory);
  const difficulty = mapDifficulty(item.difficultyText);
  const roadmap = mapRoadmap(category);

  return normalizeResource({
    id: `ref-${item.order}`,
    title: item.title,
    url: item.url,
    description: item.objective,
    category,
    difficulty,
    roadmap,
    progress: "미시작",
    tags: buildTags(item),
    summary: item.expectedOutcome,
    learningGoals: [item.objective, item.expectedOutcome],
    prepInfo: `선행지식: ${item.prerequisites}`,
    analysisNote: `추천 이유: ${item.reason} / 분석 메모: ${item.analysisMemo}`,
    notes: "",
    sourceType: "link",
    topic: item.topic,
    trustLevel: item.trustLevel,
    recommendationReason: item.reason,
    expectedOutcome: item.expectedOutcome,
    prerequisites: item.prerequisites,
    sourceCategory: item.sourceCategory,
    order: item.order,
    createdAt: "2026-03-17T16:00:00.000Z",
    updatedAt: "2026-03-17T16:00:00.000Z",
  });
});
